services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: shopoo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: shopoo
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - shopoo-network

  # Node.js Application
  app:
    build: .
    container_name: shopoo-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/shopoo?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_here
      SESSION_SECRET: your_session_secret_here
      PORT: 3000
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads
    networks:
      - shopoo-network
    command: npm run dev

  # Data Seeder (runs once to populate database)
  seeder:
    build: .
    container_name: shopoo-seeder
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/shopoo?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shopoo-network
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...' &&
        sleep 10 &&
        node scripts/seedProducts.js &&
        echo 'Seeding completed!'
      "
    restart: "no"

  # User Seeder (runs once to create users)
  user-seeder:
    build: .
    container_name: shopoo-user-seeder
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/shopoo?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shopoo-network
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...' &&
        sleep 10 &&
        node scripts/seedData.js &&
        echo 'User seeding completed!'
      "
    restart: "no"

  # MongoDB Express (Database Admin UI)
  mongo-express:
    image: mongo-express:latest
    container_name: shopoo-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - shopoo-network

  # Redis Service
  redis:
    image: redis:7
    container_name: shopoo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - shopoo-network

volumes:
  mongodb_data:

networks:
  shopoo-network:
    driver: bridge

    